# This is the pkg-config sidebar TOC.
# The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Sidebar
  product: pkg-config
  # version: 1.0
  folders:

  - title: Getting Started
    output: web
    folderitems:
    - title: Overview
      url: /dev-tools/pkg-config/
      output: web
    - title: Install
      url: /dev-tools/pkg-config/install/
      output: web
    - title: Support
      url: /dev-tools/pkg-config/support/
      output: web
    - title: FAQ
      url: /dev-tools/pkg-config/faq/
      output: web
    - title: Releases
      url: /dev-tools/pkg-config/releases/
      output: web
